apiVersion: v1
kind: Secret
metadata:
  name: target-manager-secrets
type: Opaque
stringData:
  # Recommended for Azure Postgres Flexible Server: add sslmode=require
  # Example:
  # database_url: postgresql+psycopg://monitor:YOUR_PASSWORD@defacement.postgres.database.azure.com:5432/defacement?sslmode=require
  database_url: ""
  jwt_secret: ""
  scanner_api_key: ""
