name: scanner-job

on:
  push:
    branches:
      - 'main'
#on:
  #schedule:
  #  - cron: "*/5 * * * *"  # cada 30 min
  #workflow_dispatch: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scanner/requirements.txt

      - name: Run scanner
        env:
          TARGET_MANAGER_URL: ${{ secrets.TARGET_MANAGER_URL }}
          SCANNER_API_KEY: ${{ secrets.SCANNER_API_KEY }}
          USE_SELENIUM: "0"
          SCAN_DELAY_SECONDS: "1.0"
        run: |
          python scanner/scanner_bot.py
